# Generated by Django 5.0 on 2024-02-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mix',
            old_name='name',
            new_name='title',
        ),
    ]
