# Generated by Django 5.0 on 2024-02-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0003_rename_name_mix_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
