# Generated by Django 5.0 on 2024-02-16 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_follows_followee_alter_follows_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='followed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follows',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user_api.userprofile'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='user_api.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='follows',
            unique_together={('follower', 'followee')},
        ),
    ]
