# Generated by Django 5.0 on 2024-02-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_follows_followed_at_alter_follows_followee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
    ]
