@startuml database


package user_api {
    object user {
        user_name : varchar
        email : varchar
        is_staff : boolean
        is_superuser : boolean
    }
    object user_profile {
        user_id : bigint
        full_name : varchar
        bio : varchar
        location : varchar
        avatar : varchar
    }

    object follows {
        followee_id: bigint
        follower_id: bigint
        time: now()
    }
}

package mixes {

    object mix {
        id : bigint
        user_id : bigint
        name : char(200)
        upload_time : timestamp
        filepath : char(200)
        length_in_sec : int
    }

    object predecoded_peaks {
        id : bigint
        mix_id: bigint
        normalized_peak_values : double[] 
    }

    object comment {
        user_id : bigint
        mix_id : bigint
        text : varchar(1000)
        timestamp : now()
    }

}





user <-- follows
user <-- follows
mix -> user
mix <-- predecoded_peaks
user_profile --> user
comment --> user
comment --> mix

@enduml
